Peundle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('peundle/', include('home.urls')),
    path('', include('main.urls')),
    path('admin19199266/', admin.site.urls)
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url,re_path
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    url('podcast/(?P<id>[0-9]+)$', views.podcastshow, name='podcastshow'),
    url('article/(?P<id>[0-9]+)$', views.articles, name='article'),
    path('podcast/', views.podcast, name='podcast'),
    path('sport/', views.sport, name='sport'),
    path('societe/', views.societe, name='societe'),
    path('culture/', views.culture, name='culture'),
    path('politique/', views.politique, name='politique'),
    url('homme_de_la_semaine/(?P<id>[0-9]+)$', views.homme_de_la_semaine_show, name='homme_de_la_semaine_show'),
    path('activites/', views.activites, name='activites'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('', views.index, name='index'),
]

home/models.py
from django.db import models




class Post(models.Model):
    intro = models.CharField(max_length=255, null=True, blank=True)
    legende = models.CharField(max_length=255, null=True, blank=True)
    legende2 = models.CharField(max_length=255, null=True, blank=True)
    legende3 = models.CharField(max_length=255, null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    body = models.TextField(null=True, blank=True)
    body2 = models.TextField(null=True, blank=True)
    body3 = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    image2 = models.ImageField(null=True, blank=True)
    image3 = models.ImageField(null=True, blank=True)
    author = models.CharField(max_length=255, null=True, blank=True)
    author_image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title


article_choice = {
    ('breaking', 'breaking'),
    ('actualite', 'actualite'),
    ('societe', 'societe'),
    ('culture', 'culture'),
    ('sport', 'sport'),
    ('politique', 'politique'),
    ('international', 'international'),
    ('spiritualite', 'spiritualite'),
    ('evenement', 'evenement'),
    ('activite', 'activite'),
    ('event', 'event'),
    ('video', 'video'),
    ('homme_de_la_semaine', 'homme_de_la_semaine'),
    ('business', 'business'),
    ('pub', 'pub'),

}
class Articles(models.Model):
    article_categorie = models.CharField(max_length=250, blank=True, null=True, choices=article_choice)
    intro = models.CharField(max_length=255, null=True, blank=True)
    legende = models.CharField(max_length=255, null=True, blank=True)
    legende2 = models.CharField(max_length=255, null=True, blank=True)
    legende3 = models.CharField(max_length=255, null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    body1 = models.TextField(null=True, blank=True)
    body2 = models.TextField(null=True, blank=True)
    body3 = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    image2 = models.ImageField(null=True, blank=True)
    image3 = models.ImageField(null=True, blank=True)
    author = models.CharField(max_length=255, null=True, blank=True)
    videoLink = models.CharField(max_length=255, null=True, blank=True)
    post_views = models.IntegerField(null=True, blank=True, default=0)
    comments_num = models.IntegerField(null=True, blank=True, default=0)
    

    def __str__(self):
        return self.title


class Episode(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    topic = models.CharField(max_length=255, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    link = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title


class Album(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    image1 = models.ImageField()
    image2 = models.ImageField()
    image3 = models.ImageField()
    image4 = models.ImageField()
    image5 = models.ImageField()
    author = models.CharField(max_length=255)
    author_image = models.ImageField()

    def __str__(self):
        return self.title


class Homme_de_la_semaine(models.Model):
    legende = models.CharField(max_length=255, null=True, blank=True)
    legende2 = models.CharField(max_length=255, null=True, blank=True)
    legende3 = models.CharField(max_length=255, null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    body1 = models.TextField(null=True, blank=True)
    body2 = models.TextField(null=True, blank=True)
    body3 = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    image2 = models.ImageField(null=True, blank=True)
    image3 = models.ImageField(null=True, blank=True)
    author = models.CharField(max_length=255, null=True, blank=True)
    author_image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title


class Comment_Article(models.Model):
    article = models.ForeignKey(Articles, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=255)
    email = models.EmailField()
    content = models.TextField(null=True, blank=True)
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        ordering = ("publish",)
        
    def __str__(self):
        return '%s - %s' % (self.article.title, self.name) 
    

video_categorie_choice = {
    ('sport', 'sport'),
    ('societe', 'societe'),
    ('culture', 'culture'),
    ('activite', 'activite'),
}

class A_voir(models.Model):
    categorie = models.CharField(max_length=255, choices=video_categorie_choice)
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    videoLink = models.CharField(max_length=255)
    author = models.CharField(max_length=255)

    def __str__(self):
        return self.title



class Partenaires(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title

home/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
import requests
import http.client
from django.contrib.auth.models import User
from django.shortcuts import get_list_or_404, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as django_logout
from .models import Post
from .models import Articles
from .models import A_voir
from .models import Album
from .models import Homme_de_la_semaine
from .models import Partenaires
from .models import Episode
from .models import Comment_Article
from datetime import datetime, timedelta, time


def index(request):
    user = request.user
    posts = Post.objects.all()
    return render(request, 'index.html', {'posts': posts})


def articles(request, id):
    user = request.user
    articles = Articles.objects.all().order_by('-date')
    partenaire = Partenaires.objects.all()
    videos = A_voir.objects.filter(categorie="societe").order_by('-date')
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')
    actu_articles = Articles.objects.filter(article_categorie='actualite').order_by('-date')
    societe_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    politique_articles = Articles.objects.filter(article_categorie='politique').order_by('-date')
    sport_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    culture_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    spiritualite_articles = Articles.objects.filter(article_categorie='spiritualite').order_by('-date')
    article = Articles.objects.get(pk=id)
    post_views = None
    comments_num = None
    if article:
        article.post_views = article.post_views + 1
        article.save()
    comments = Comment_Article.objects.filter(article=article.id).order_by('-date')
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        content = request.POST['content']
        new_comment = Comment_Article(name=name, email=email, content=content)
        new_comment.article = article
        new_comment.save()

        if new_comment: 
            article.comments_num = article.comments_num + 1
            article.save()
            
        return redirect(request.path)
    comments_count = Comment_Article.objects.filter(article=article.id).count()
    context = {
        'articles': articles,
        'article': article, 
        'videos': videos, 
        'partenaire' : partenaire, 
        'comments' : comments,
        'comments_count' : comments_count,
        'actu_articles': actu_articles,
        'societe_articles': societe_articles,
        'politique_articles': politique_articles,
        'sport_articles': sport_articles,
        'culture_articles': culture_articles,
        'spiritualite_articles': spiritualite_articles,
        'international_articles': international_articles,
        'post_views': post_views,
    }
    
    return render(request, 'article.html', context)

def activites(request):
    user = request.user
    articles = Articles.objects.all().order_by('-date')
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')
    actu_articles = Articles.objects.filter(article_categorie='actualite').order_by('-date')
    societe_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    politique_articles = Articles.objects.filter(article_categorie='politique').order_by('-date')
    sport_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    culture_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    cat_articles = Articles.objects.filter(article_categorie='activite').order_by('-date')
    spiritualite_articles = Articles.objects.filter(article_categorie='spiritualite').order_by('-date')
    partenaire = Partenaires.objects.all()
    videos = A_voir.objects.filter(categorie="activite").order_by('-date')
    
    context = {
        'videos': videos, 
        'partenaire': partenaire,
        'actu_articles': actu_articles,
        'societe_articles': societe_articles,
        'politique_articles': politique_articles,
        'sport_articles': sport_articles,
        'culture_articles': culture_articles,
        'spiritualite_articles': spiritualite_articles,
        'international_articles': international_articles,
        'cat_articles': cat_articles,
        'articles': articles,
    }
    return render(request, 'activites.html', context)

def sport(request, categorie=None):
    user = request.user
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')
    actu_articles = Articles.objects.filter(article_categorie='actualite').order_by('-date')
    societe_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    politique_articles = Articles.objects.filter(article_categorie='politique').order_by('-date')
    sport_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    culture_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    spiritualite_articles = Articles.objects.filter(article_categorie='spiritualite').order_by('-date')
    activite_articles = Articles.objects.filter(article_categorie='activite').order_by('-date')
    partenaire = Partenaires.objects.all()
    player_of_week = Homme_de_la_semaine.objects.all().order_by('-date')
    videos = A_voir.objects.filter(categorie="sport").order_by('-date')
    posts = Post.objects.all().order_by('-date')
    articles = Articles.objects.all().order_by('-date')
    cat_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    

    if categorie is None:
        context = {
        'player_of_week': player_of_week, 
        'posts':posts, 
        'videos': videos,
        'partenaire' : partenaire,
        'articles': articles,
        'cat_articles': cat_articles,
        'actu_articles': actu_articles,
        'societe_articles': societe_articles,
        'politique_articles': politique_articles,
        'sport_articles': sport_articles,
        'culture_articles': culture_articles,
        'spiritualite_articles': spiritualite_articles,
        'international_articles': international_articles,
        'activite_articles': activite_articles,
    }
        
        return render(request, 'sport.html', context)
    else:
        pass


def societe(request):
    user = request.user
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')
    actu_articles = Articles.objects.filter(article_categorie='actualite').order_by('-date')
    societe_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    politique_articles = Articles.objects.filter(article_categorie='politique').order_by('-date')
    sport_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    culture_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    spiritualite_articles = Articles.objects.filter(article_categorie='spiritualite').order_by('-date')
    partenaire = Partenaires.objects.all()
    videos = A_voir.objects.filter(categorie="societe").order_by('-date')
    articles = Articles.objects.all().order_by('-date')
    cat_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    
    context = {
        'actu_articles': actu_articles,
        'societe_articles': societe_articles,
        'politique_articles': politique_articles,
        'sport_articles': sport_articles,
        'culture_articles': culture_articles,
        'spiritualite_articles': spiritualite_articles,
        'international_articles': international_articles,
        'articles':articles, 
        'videos': videos, 
        'partenaire' : partenaire, 
        'cat_articles': cat_articles
    }
    return render(request, 'societe.html', context)


def culture(request):
    user = request.user
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')
    actu_articles = Articles.objects.filter(article_categorie='actualite').order_by('-date')
    societe_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    politique_articles = Articles.objects.filter(article_categorie='politique').order_by('-date')
    sport_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    culture_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    spiritualite_articles = Articles.objects.filter(article_categorie='spiritualite').order_by('-date')
    activite_articles = Articles.objects.filter(article_categorie='activite').order_by('-date')
    partenaire = Partenaires.objects.all()
    articles = Articles.objects.all().order_by('-date')
    videos = A_voir.objects.filter(categorie="culture")
    cat_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    
    context = {
        'videos': videos,
        'activites' : activites,
        'articles': articles,
        'partenaire' : partenaire,
        'cat_articles' : cat_articles,
        'actu_articles': actu_articles,
        'societe_articles': societe_articles,
        'politique_articles': politique_articles,
        'sport_articles': sport_articles,
        'culture_articles': culture_articles,
        'spiritualite_articles': spiritualite_articles,
        'international_articles': international_articles,
        'activite_articles': activite_articles,
        
    }
    return render(request, 'culture.html', context)



def politique(request):
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')

home/templates/activites.html
{% extends 'layouts/base2.html' %}
	{% block content %}


		<!-- block-wrapper-section
			================================================== -->
		<section class="block-wrapper">
			<div class="container">
				<div class="row">
					{% include 'layouts/all_article_cat.html' %}

					<div class="col-sm-4">

						<!-- sidebar -->
						<div class="sidebar">

							{% include 'layouts/share.html' %}

							{% include 'layouts/right_content.html' %}
												
							{% include 'layouts/video.html' %}
						</div>
						<!-- End sidebar -->

					</div>

				</div>

			</div>
		</section>
		<!-- End block-wrapper-section -->

        {% endblock %}

home/templates/actu.html
{% extends 'layouts/base2.html' %}
{% load social_share %}
	{% block content %}

		<!-- block-wrapper-section
			================================================== -->
		<section class="block-wrapper">

			<div class="container">
				<div class="row">
					<div class="col-sm-8">

						<!-- block content -->
						<div class="block-content">

							<!-- single-post box -->
							<div class="single-post-box">

								<div class="title-post">
									<h1>{{actu.title}} </h1>
									<ul class="post-tags">
										<li><i class="fa fa-clock-o"></i>{{actu.date| date:"d F Y"}}</li>
										<li><i class="fa fa-user"></i>Par <a href="#">{{actu.author}}</a></li>
										<li><a href="#"><i class="fa fa-comments-o"></i><span>0</span></a></li>
										<li><i class="fa fa-eye"></i>872</li>
									</ul>
								</div>

								{% include 'layouts/social_share.html' %}

								<div class="post-gallery">
									<ul class="bxslider">
										<li><img src="{{actu.image.url}}" alt=""></li>
										{% if actu.image.2%}
										<li><img src="{{actu.image2.url}}" alt=""></li>
										{% endif %}
									</ul>
									<span class="image-caption">{{actu.legende}}</span>
								</div>

								<div class="post-content">

									<p>{{actu.body1|linebreaks }}</p>

									{% if actu.body2 %}
									<h2>{{actu.body2|linebreaks }} </h2>
									{% endif %}
									
								</div>

								<div class="post-gallery">
									{% if actu.image2 %}
									<img src="{{actu.image2.url}}" id="middle-post-gallery" alt="">
									<span class="image-caption">{{actu.legende2}}.</span>
									{% endif %}
								</div>

								<div class="post-content">

									{% if actu.body3 %}
									<p>{{actu.body3|linebreaks }}</p>
									{% endif %}

								</div>

								<div class="article-inpost">
									<div class="row">
										{% if actu.image3 %}
										<div class="col-md-6">
											<div class="image-content">
												<div class="image-place">
													<img src="{{actu.image3.url}}" alt="">
													<div class="hover-image">
														<a class="zoom" href="{{actu.image3.url}}"><i class="fa fa-arrows-alt"></i></a>
													</div>
												</div>
												<span class="image-caption">{{actu.legende3}}.</span>
											</div>
										</div>
										{% endif %}
										{% if actu.image %}
										<div class="col-md-6">
											<div class="image-content">
												<div class="image-place">
													<img src="{{actu.image.url}}" alt="">
													<div class="hover-image">
														<a class="zoom" href="{{actu.image.url}}"><i class="fa fa-arrows-alt"></i></a>
													</div>
												</div>
												<span class="image-caption">{{actu.legende}}.</span>
											</div>
										</div>
										{% endif %}
									</div>
								</div>


								<!-- contact form box -->
								<div class="contact-form-box">
									<div class="title-section">
										<h1><span>Commenter</span> <span class="email-not-published">Votre e-mail n'apparaîtra pas.</span></h1>
									</div>
									<form method="POST" id="comment-form">
										{% csrf_token %}
										<div class="row">
											<div class="col-md-4">
												<label for="name">Nom & Prénom*</label>
												<input id="name" name="name" type="text">
											</div>
											<div class="col-md-4">
												<label for="mail">E-mail*</label>
												<input id="mail" name="email" type="text">
											</div>
										</div>
										<label for="comment">Commentaire*</label>
										<textarea id="comment" name="content"></textarea>
										<button type="submit" id="comment-actu" name="comment-actu">
											<i class="fa fa-comment"></i> Valider
										</button>
									</form>
								</div>
								<!-- End contact form box -->

							</div>
							<!-- End single-post box -->

						</div>
						<!-- End block content -->
						<div class="title-section">
							<h1><span>Commentaires</h1>
						</div>

						{% include 'layouts/comment.html' %}
					</div>

					<div class="col-sm-4">

						<!-- sidebar -->
						<div class="sidebar">

							{% include 'layouts/share.html' %}

							<div class="widget features-slide-widget">
								<div class="title-section">
									<h1><span>Autres actus</span></h1>
								</div>
								<div class="news-post standard-post2">
									{% for element in actus %}
									{% if forloop.counter == 2 and element != actu %}
									<div class="post-gallery">
										<img src="{{element.image.url}}" alt="">
									</div>
									<div class="post-title">
										<h2><a href="{% url 'home:actu' id=element.id %}">{{element.title}}</a></h2>
										<ul class="post-tags">
											<li><i class="fa fa-clock-o"></i>{{element.date| date:"d F Y"}}</li>
											<li><i class="fa fa-user"></i>by <a href="#">{{element.author}}</a></li>
											<li><a href="#"><i class="fa fa-comments-o"></i><span>23</span></a></li>
											<li><i class="fa fa-eye"></i>872</li>
										</ul>
									</div>
									<br>
									{% endif %}
									{% endfor %}
								</div>
							</div>

							{% include 'layouts/right_content.html' %}
							{% include 'layouts/video.html' %}
							{% include 'layouts/tags.html' %}



							

						</div>
						<!-- End sidebar -->

					</div>

				</div>

			</div>
		</section>
		<!-- End block-wrapper-section -->

	{% endblock %}

home/templates/culture.html
{% extends 'layouts/base2.html' %}

	{% block content %}


		<!-- block-wrapper-section
			================================================== -->
		<section class="block-wrapper">
			<div class="container">
				<div class="row">
					{% include 'layouts/all_article_cat.html' %}
					<div class="col-sm-4">

						<!-- sidebar -->
						<div class="sidebar">

						{% include 'layouts/share.html' %}

						{% include 'layouts/right_content2.html' %}

							

						{% include 'layouts/video.html'%}
						{% include 'layouts/tags.html'%}

						</div>
						<!-- End sidebar -->

					</div>

				</div>

			</div>
		</section>
		<!-- End block-wrapper-section -->

		{% endblock %}

home/templates/homme_show.html
{% extends 'layouts/base2.html' %}
	{% block content %}


		<!-- block-wrapper-section
			================================================== -->
		<section class="block-wrapper">
			<div class="container">
				<div class="row">
					{% include 'layouts/all_article_cat.html' %}

					<div class="col-sm-4">

						<!-- sidebar -->
						<div class="sidebar">

							{% include 'layouts/share.html' %}

							{% include 'layouts/right_content.html' %}
												
							{% include 'layouts/video.html' %}
						</div>
						<!-- End sidebar -->

					</div>

				</div>

			</div>
		</section>
		<!-- End block-wrapper-section -->

        {% endblock %}

home/templates/index.html
{% extends 'layouts/base.html' %}
	{% block content %}

	<div id="colorlib-main">
		<section class="ftco-section ftco-no-pt ftco-no-pb">
			<div class="container px-md-0">
				<div class="row g-0">
					<div class="col-sm-6 col-md-8">
						<div class="row d-flex no-gutters">
							<div class="section-title">
							<h2>APEX TV</h2>
							</div>
						</div>
					</div>
            	</div>

				<div class="embed-responsive embed-responsive-16by9">
					<iframe width="560" height="315" src="#" alt="Pas de live en cours" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
				</div>

				<div class="row d-flex">
					<div class="col-md-12">
						<a href="#" class="btn-custom-load d-block w-100 text-center py-4">Vous êtes sur APEX LIVE TV </span></a>
					</div>
				</div>
			</div>
		</section>
	</div>

{% endblock %}

home/templates/podcast.html
{% extends 'layouts/base.html' %}
	{% block content %}

			<div id="colorlib-main">
				<section class="ftco-section ftco-no-pt ftco-no-pb">
					<div class="container px-md-0" >
						<div class="row g-0">
							<div class="col-sm-6 col-md-8">
								<div class="row d-flex no-gutters">
									<div class="section-title">
									<h2>PODCASTS</h2>
									</div>
									{% for element in episodes %}
									{% if forloop.counter <= 2 %}
									<div class="card mb-3" id="podcast">
									  <img src="{{element.image.url}}" class="card-img-top" alt="...">
									  <div class="card-body">
										<h5 class="card-title">{{element.title}}</h5>
										<p class="card-text">{{element.topic}}</p>
										<p><a href="{% url 'home:podcastshow' id=element.id %}" class="btn-custom">Ecouter <i class="fa-solid fa-play"></i></a></p>
										<p class="card-text"><small class="text-muted">{{element.date}}</small></p>
									  </div>
									</div>
									{% endif %}
									{% endfor %}
								</div>
							</div>
							<div class="col-6 col-md-4" id="list-card">
								{% for element in episodes %}
								{% if forloop.counter > 2 %}
								<div class="list-group">
								  <a href="{% url 'home:podcastshow' id=element.id %}" class="list-group-item list-group-item-action" aria-current="true">
									<div class="d-flex w-100 justify-content-between">
									  <h5 class="mb-1">{{element.title}}</h5>
									</div>
									<p class="mb-1">{{element.topic}}</p>
									<small>{{element.date}}</small>
								  </a>
								</div>
								{% endif %}
								{% endfor %}
							</div>
						</div>
						<div class="list-group" id="list-card-mobile">
						{% for element in episodes %}
						{% if forloop.counter > 2 %}
						  <a href="{% url 'home:podcastshow' id=element.id %}" class="list-group-item list-group-item-action" aria-current="true">
							<div class="d-flex w-100 justify-content-between">
							  <h5 class="mb-1">{{element.title}}</h5>
							</div>
							<p class="mb-1">{{element.topic}}</p>
							<small>{{element.date}}</small>
						  </a>
						{% endif %}
						{% endfor %}
						</div>
					</div>
				</section>
			</div>

    {% endblock %}

home/templates/sport.html
{% extends 'layouts/base2.html' %}
	{% block content %}


		<!-- block-wrapper-section
			================================================== -->
		<section class="block-wrapper">
			<div class="container">
				<div class="row">
					{% include 'layouts/all_article_cat.html' %}

					<div class="col-sm-4">

						<!-- sidebar -->
						<div class="sidebar">
							{% include 'layouts/share.html' %}

							<div class="widget features-slide-widget">
								<div class="title-section">
									<h1><span>ON EN PARLE</span></h1>
								</div>
								{% for element in actu_articles %}
								{% if forloop.counter == 1 %}
								<div class="news-post standard-post2">
									<div class="post-gallery">
										<img src="{{element.image.url}}" alt="">
									</div>
									<div class="post-title">
										<h2><a href="single-post.html">{{element.title}}</a></h2>
										<ul class="post-tags">
											<li><i class="fa fa-user"></i>Par <a href="#">{{element.author}}</a></li>
											<li><a href="#"><i class="fa fa-comments-o"></i><span>{{element.comments_num}}</span></a></li>
											<li><i class="fa fa-eye"></i>{{element.post_views}}</li>
										</ul>
									</div>
								</div>
								{% endif %}
								{% endfor %}
							</div>

							<div class="widget tab-posts-widget">

								<ul class="nav nav-tabs" id="myTab">
									<li class="active">
										<a href="#option1" data-toggle="tab">Activités</a>
									</li>
									<li>
										<a href="#option2" data-toggle="tab">Culture</a>
									</li>
									<li>
										<a href="#option3" data-toggle="tab">Evènements</a>
									</li>
								</ul>

								<div class="tab-content">
									<div class="tab-pane active" id="option1">
										<ul class="list-posts">
										{% for element in activite_articles %}
										{% if forloop.counter < 6 %}
											<li>
												<img src="{{element.image.url}}" alt="">
												<div class="post-content">
													<h2><a href="{% url 'home:article' element.id %}">{{element.title}} </a></h2>
													<ul class="post-tags">
														<li><i class="fa fa-clock-o"></i>{{element.date}}</li>
													</ul>
												</div>
											</li>
										{% endif %}
										{% endfor %}
										</ul>
									</div>
									<div class="tab-pane" id="option2">
										<ul class="list-posts">
											{% for element in culture_articles %}
											{% if forloop.counter < 6 %}
											<li>
												<img src="{{element.image.url}}" alt="">
												<div class="post-content">
													<h2><a href="{% url 'home:article' element.id %}">{{element.title}}</a></h2>
													<ul class="post-tags">
														<li><i class="fa fa-clock-o"></i>{{element.date}}</li>
													</ul>
												</div>
											</li>
											{% endif %}
											{% endfor %}
										</ul>
									</div>
									<div class="tab-pane" id="option3">
										<ul class="list-posts">
											{% for element in events %}
											{% if forloop.counter < 6 %}
											<li>
												<img src="{{element.image.url}}" alt="">
												<div class="post-content">
													<h2><a href="{% url 'home:event_show' element.id %}">{{element.title}} </a></h2>
													<ul class="post-tags">
														<li><i class="fa fa-clock-o"></i>{{element.date| date:"d F Y"}}</li>
													</ul>
												</div>
											</li>
											{% endif %}
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>

							{% include 'layouts/video.html' %}
							{% include 'layouts/tags.html' %}

						</div>
						<!-- End sidebar -->

					</div>

				</div>

			</div>
		</section>
		<!-- End block-wrapper-section -->

		{% endblock %}