Peundle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('peundle/', include('home.urls')),
    path('', include('main.urls')),
    path('admin19199266/', admin.site.urls)
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url,re_path
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    url('podcast/(?P<id>[0-9]+)$', views.podcastshow, name='podcastshow'),
    url('article/(?P<id>[0-9]+)$', views.articles, name='article'),
    path('podcast/', views.podcast, name='podcast'),
    path('sport/', views.sport, name='sport'),
    path('societe/', views.societe, name='societe'),
    path('culture/', views.culture, name='culture'),
    path('politique/', views.politique, name='politique'),
    url('homme_de_la_semaine/(?P<id>[0-9]+)$', views.homme_de_la_semaine_show, name='homme_de_la_semaine_show'),
    path('activites/', views.activites, name='activites'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('', views.index, name='index'),
]

main/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.mainpage, name='mainpage'),
]

home/models.py
from django.db import models




class Post(models.Model):
    intro = models.CharField(max_length=255, null=True, blank=True)
    legende = models.CharField(max_length=255, null=True, blank=True)
    legende2 = models.CharField(max_length=255, null=True, blank=True)
    legende3 = models.CharField(max_length=255, null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    body = models.TextField(null=True, blank=True)
    body2 = models.TextField(null=True, blank=True)
    body3 = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    image2 = models.ImageField(null=True, blank=True)
    image3 = models.ImageField(null=True, blank=True)
    author = models.CharField(max_length=255, null=True, blank=True)
    author_image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title


article_choice = {
    ('breaking', 'breaking'),
    ('actualite', 'actualite'),
    ('societe', 'societe'),
    ('culture', 'culture'),
    ('sport', 'sport'),
    ('politique', 'politique'),
    ('international', 'international'),
    ('spiritualite', 'spiritualite'),
    ('evenement', 'evenement'),
    ('activite', 'activite'),
    ('event', 'event'),
    ('video', 'video'),
    ('homme_de_la_semaine', 'homme_de_la_semaine'),
    ('business', 'business'),
    ('pub', 'pub'),

}
class Articles(models.Model):
    article_categorie = models.CharField(max_length=250, blank=True, null=True, choices=article_choice)
    intro = models.CharField(max_length=255, null=True, blank=True)
    legende = models.CharField(max_length=255, null=True, blank=True)
    legende2 = models.CharField(max_length=255, null=True, blank=True)
    legende3 = models.CharField(max_length=255, null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    body1 = models.TextField(null=True, blank=True)
    body2 = models.TextField(null=True, blank=True)
    body3 = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    image2 = models.ImageField(null=True, blank=True)
    image3 = models.ImageField(null=True, blank=True)
    author = models.CharField(max_length=255, null=True, blank=True)
    videoLink = models.CharField(max_length=255, null=True, blank=True)
    post_views = models.IntegerField(null=True, blank=True, default=0)
    comments_num = models.IntegerField(null=True, blank=True, default=0)
    

    def __str__(self):
        return self.title


class Episode(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    topic = models.CharField(max_length=255, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    link = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title


class Album(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    image1 = models.ImageField()
    image2 = models.ImageField()
    image3 = models.ImageField()
    image4 = models.ImageField()
    image5 = models.ImageField()
    author = models.CharField(max_length=255)
    author_image = models.ImageField()

    def __str__(self):
        return self.title


class Homme_de_la_semaine(models.Model):
    legende = models.CharField(max_length=255, null=True, blank=True)
    legende2 = models.CharField(max_length=255, null=True, blank=True)
    legende3 = models.CharField(max_length=255, null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    body1 = models.TextField(null=True, blank=True)
    body2 = models.TextField(null=True, blank=True)
    body3 = models.TextField(null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    image2 = models.ImageField(null=True, blank=True)
    image3 = models.ImageField(null=True, blank=True)
    author = models.CharField(max_length=255, null=True, blank=True)
    author_image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title


class Comment_Article(models.Model):
    article = models.ForeignKey(Articles, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=255)
    email = models.EmailField()
    content = models.TextField(null=True, blank=True)
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        ordering = ("publish",)
        
    def __str__(self):
        return '%s - %s' % (self.article.title, self.name) 
    

video_categorie_choice = {
    ('sport', 'sport'),
    ('societe', 'societe'),
    ('culture', 'culture'),
    ('activite', 'activite'),
}

class A_voir(models.Model):
    categorie = models.CharField(max_length=255, choices=video_categorie_choice)
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    videoLink = models.CharField(max_length=255)
    author = models.CharField(max_length=255)

    def __str__(self):
        return self.title



class Partenaires(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title

home/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
import requests
import http.client
from django.contrib.auth.models import User
from django.shortcuts import get_list_or_404, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as django_logout
from .models import Post
from .models import Articles
from .models import A_voir
from .models import Album
from .models import Homme_de_la_semaine
from .models import Partenaires
from .models import Episode
from .models import Comment_Article
from datetime import datetime, timedelta, time


def index(request):
    user = request.user
    posts = Post.objects.all()
    return render(request, 'index.html', {'posts': posts})


def articles(request, id):
    user = request.user
    articles = Articles.objects.all().order_by('-date')
    partenaire = Partenaires.objects.all()
    videos = A_voir.objects.filter(categorie="societe").order_by('-date')
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')
    actu_articles = Articles.objects.filter(article_categorie='actualite').order_by('-date')
    societe_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    politique_articles = Articles.objects.filter(article_categorie='politique').order_by('-date')
    sport_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    culture_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    spiritualite_articles = Articles.objects.filter(article_categorie='spiritualite').order_by('-date')
    article = Articles.objects.get(pk=id)
    post_views = None
    comments_num = None
    if article:
        article.post_views = article.post_views + 1
        article.save()
    comments = Comment_Article.objects.filter(article=article.id).order_by('-date')
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        content = request.POST['content']
        new_comment = Comment_Article(name=name, email=email, content=content)
        new_comment.article = article
        new_comment.save()

        if new_comment: 
            article.comments_num = article.comments_num + 1
            article.save()
            
        return redirect(request.path)
    comments_count = Comment_Article.objects.filter(article=article.id).count()
    context = {
        'articles': articles,
        'article': article, 
        'videos': videos, 
        'partenaire' : partenaire, 
        'comments' : comments,
        'comments_count' : comments_count,
        'actu_articles': actu_articles,
        'societe_articles': societe_articles,
        'politique_articles': politique_articles,
        'sport_articles': sport_articles,
        'culture_articles': culture_articles,
        'spiritualite_articles': spiritualite_articles,
        'international_articles': international_articles,
        'post_views': post_views,
    }
    
    return render(request, 'article.html', context)

def activites(request):
    user = request.user
    articles = Articles.objects.all().order_by('-date')
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')
    actu_articles = Articles.objects.filter(article_categorie='actualite').order_by('-date')
    societe_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    politique_articles = Articles.objects.filter(article_categorie='politique').order_by('-date')
    sport_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    culture_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    cat_articles = Articles.objects.filter(article_categorie='activite').order_by('-date')
    spiritualite_articles = Articles.objects.filter(article_categorie='spiritualite').order_by('-date')
    partenaire = Partenaires.objects.all()
    videos = A_voir.objects.filter(categorie="activite").order_by('-date')
    
    context = {
        'videos': videos, 
        'partenaire': partenaire,
        'actu_articles': actu_articles,
        'societe_articles': societe_articles,
        'politique_articles': politique_articles,
        'sport_articles': sport_articles,
        'culture_articles': culture_articles,
        'spiritualite_articles': spiritualite_articles,
        'international_articles': international_articles,
        'cat_articles': cat_articles,
        'articles': articles,
    }
    return render(request, 'activites.html', context)

def sport(request, categorie=None):
    user = request.user
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')
    actu_articles = Articles.objects.filter(article_categorie='actualite').order_by('-date')
    societe_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    politique_articles = Articles.objects.filter(article_categorie='politique').order_by('-date')
    sport_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    culture_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    spiritualite_articles = Articles.objects.filter(article_categorie='spiritualite').order_by('-date')
    activite_articles = Articles.objects.filter(article_categorie='activite').order_by('-date')
    partenaire = Partenaires.objects.all()
    player_of_week = Homme_de_la_semaine.objects.all().order_by('-date')
    videos = A_voir.objects.filter(categorie="sport").order_by('-date')
    posts = Post.objects.all().order_by('-date')
    articles = Articles.objects.all().order_by('-date')
    cat_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    

    if categorie is None:
        context = {
        'player_of_week': player_of_week, 
        'posts':posts, 
        'videos': videos,
        'partenaire' : partenaire,
        'articles': articles,
        'cat_articles': cat_articles,
        'actu_articles': actu_articles,
        'societe_articles': societe_articles,
        'politique_articles': politique_articles,
        'sport_articles': sport_articles,
        'culture_articles': culture_articles,
        'spiritualite_articles': spiritualite_articles,
        'international_articles': international_articles,
        'activite_articles': activite_articles,
    }
        
        return render(request, 'sport.html', context)
    else:
        pass


def societe(request):
    user = request.user
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')
    actu_articles = Articles.objects.filter(article_categorie='actualite').order_by('-date')
    societe_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    politique_articles = Articles.objects.filter(article_categorie='politique').order_by('-date')
    sport_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    culture_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    spiritualite_articles = Articles.objects.filter(article_categorie='spiritualite').order_by('-date')
    partenaire = Partenaires.objects.all()
    videos = A_voir.objects.filter(categorie="societe").order_by('-date')
    articles = Articles.objects.all().order_by('-date')
    cat_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    
    context = {
        'actu_articles': actu_articles,
        'societe_articles': societe_articles,
        'politique_articles': politique_articles,
        'sport_articles': sport_articles,
        'culture_articles': culture_articles,
        'spiritualite_articles': spiritualite_articles,
        'international_articles': international_articles,
        'articles':articles, 
        'videos': videos, 
        'partenaire' : partenaire, 
        'cat_articles': cat_articles
    }
    return render(request, 'societe.html', context)


def culture(request):
    user = request.user
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')
    actu_articles = Articles.objects.filter(article_categorie='actualite').order_by('-date')
    societe_articles = Articles.objects.filter(article_categorie='societe').order_by('-date')
    politique_articles = Articles.objects.filter(article_categorie='politique').order_by('-date')
    sport_articles = Articles.objects.filter(article_categorie='sport').order_by('-date')
    culture_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    spiritualite_articles = Articles.objects.filter(article_categorie='spiritualite').order_by('-date')
    activite_articles = Articles.objects.filter(article_categorie='activite').order_by('-date')
    partenaire = Partenaires.objects.all()
    articles = Articles.objects.all().order_by('-date')
    videos = A_voir.objects.filter(categorie="culture")
    cat_articles = Articles.objects.filter(article_categorie='culture').order_by('-date')
    
    context = {
        'videos': videos,
        'activites' : activites,
        'articles': articles,
        'partenaire' : partenaire,
        'cat_articles' : cat_articles,
        'actu_articles': actu_articles,
        'societe_articles': societe_articles,
        'politique_articles': politique_articles,
        'sport_articles': sport_articles,
        'culture_articles': culture_articles,
        'spiritualite_articles': spiritualite_articles,
        'international_articles': international_articles,
        'activite_articles': activite_articles,
        
    }
    return render(request, 'culture.html', context)



def politique(request):
    international_articles = Articles.objects.filter(article_categorie='international').order_by('-date')

home/templates/layouts/all_article_cat.html
<div class="col-sm-8">
    <div class="block-content">

        <!-- grid box -->
        <div class="grid-box">
            <div class="title-section">
                <h1><span>{% block title %}NEWS{% endblock title %}
                </span></h1>
            </div>

            <div class="image-slider">
                <ul class="bxslider">
                    {% for element in cat_articles %}
                    {% if forloop.counter <= 2 %}
                    <li>
                        <div class="news-post image-post" id="foot_posts">
                            <img src="{{element.image.url}}" alt="">
                            <div class="hover-box">
                                <div class="inner-hover">
                                    <h2><a href="{% url 'home:article' id=element.id %}">{{element.title}}</a></h2>
                                    <ul class="post-tags">
                                        <li><i class="fa fa-clock-o"></i>{{element.date| date:"d F Y"}}</li>
                                        <li><a href="#"><i class="fa fa-comments-o"></i><span>{{element.comments_num}}</span></a></li>
                                        <li><i class="fa fa-eye"></i>{{element.post_views}}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>

            <div class="row">
            {% for element in cat_articles %}
            {% if forloop.counter > 2 %}
                <div class="col-md-6">
                    <div class="news-post standard-post2">
                        <div class="post-gallery">
                            <img src="{{element.image.url}}" alt="">
                        </div>
                        <div class="post-title">
                            <h2><a href="{% url 'home:article' id=element.id %}">{{element.title}}</a></h2>
                            <ul class="post-tags">
                                <li><i class="fa fa-user"></i>Par <a href="#">{{element.author}}</a></li>
                                <li><a href="#"><i class="fa fa-comments-o"></i><span>{{element.comments_num}}</span></a></li>
                                <li><i class="fa fa-eye"></i>{{element.post_views}}</li>
                            </ul>
                        </div>
                        <div class="post-content">
                            <p>{{element.body | truncatewords:20}}</p>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <!-- End grid box -->

        <!-- pagination box -->
        <div class="pagination-box">
            <ul class="pagination-list">
                <li><a class="active" href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><span>...</span></li>
                <li><a href="#">9</a></li>
                <li><a href="#">Suivant</a></li>
            </ul>
            <p>Page 1 sur 9</p>
        </div>
        <!-- End Pagination box -->

    </div>
    <!-- End block content -->

</div>

home/templates/layouts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>APEX TV</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'home/css/animate.css' %}">

	<link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'home/css/owl.theme.default.min.css' %}">
	<link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}">


	<link rel="stylesheet" href="{% static 'home/css/flaticon.css' %}">
	<link rel="stylesheet" href="{% static 'home/css/style.css' %}">
</head>
<body>

	<div id="colorlib-page">
		<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
		<aside id="colorlib-aside" role="complementary" class="js-fullheight">

			<h1 id="colorlib-logo" class="mb-4 mb-md-5"><a href="{% url 'home:index' %}" style="background-image: url(/static/images/jaune25.avif);">APEX</a><br><span>MediaTV</span></h1>
			<nav id="colorlib-main-menu" role="navigation">
				{% with request.resolver_match.url_name as url_name %}
				<ul>
					<li class="{% if url_name == 'index' %}colorlib-active{% endif %}"><a href="{% url 'home:index' %}">Live</a></li>
					<li class="{% if url_name == 'podcast' %}colorlib-active{% endif %}"><a href="{% url 'home:podcast' %}">Podcast</a></li>
					<li class="{% if url_name == 'explore' %}colorlib-active{% endif %}"><a href="{% url 'main:mainpage' %}">Retour</a></li>
				</ul>
				{% endwith %}
			</nav>

			</aside> <!-- END COLORLIB-ASIDE -->

		{% block content %}

		{% endblock %}


		<!-- loader -->
		<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


		<script src="{% static 'home/js/jquery.min.js' %}"></script>
		<script src="{% static 'home/js/jquery-migrate-3.0.1.min.js' %}"></script>
		<script src="{% static 'home/js/popper.min.js' %}"></script>
		<script src="{% static 'home/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'home/js/jquery.easing.1.3.js' %}"></script>
		<script src="{% static 'home/js/jquery.waypoints.min.js' %}"></script>
		<script src="{% static 'home/js/jquery.stellar.min.js' %}"></script>
		<script src="{% static 'home/js/owl.carousel.min.js' %}"></script>
		<script src="{% static 'home/js/jquery.magnific-popup.min.js' %}"></script>
		<script src="{% static 'home/js/jquery.animateNumber.min.js' %}"></script>
		<script src="{% static 'home/js/scrollax.min.js' %}"></script>
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
		<script src="{% static 'home/js/google-map.js' %}"></script>
		<script src="{% static 'home/js/main.js' %}"></script>

	</div>
	</body>
	</html>

home/templates/layouts/comments.html
<div class="title-section">
<h1><span>Commentaires</h1></span>
</div>
{% for element in comments %}

<div class="panel panel-default">
    <div class="panel-body">
      {{element.content}}
    </div>
    <div class="panel-footer">Par : {{element.name}}</div>
</div>

{% endfor %}

home/templates/layouts/right_content.html
<div class="widget features-slide-widget">
    <div class="title-section">
        <h1><span>ON EN PARLE</span></h1>
    </div>
    {% for element in politique_articles %}
    {% if element.article_categorie == "politique" %}
    {% if forloop.counter <= 2 %}

    <div class="news-post standard-post2">
        <div class="post-gallery">
            <img src="{{element.image.url}}" alt="">
        </div>
        <div class="post-title">
            <h2><a href="{% url 'home:article' element.id %}">{{element.title}}</a></h2>
            <ul class="post-tags">
                <li><i class="fa fa-clock-o"></i>{{element.date| date:"d F Y"}}</li>
                <li><i class="fa fa-user"></i>Par <a href="#">{{element.author}}</a></li>
                <li><a href="#"><i class="fa fa-comments-o"></i><span>{{element.comments_num}}</span></a></li>
                <li><i class="fa fa-eye"></i>{{element.post_views}}</li>
            </ul>
        </div>
    </div>
    <br>
    {% endif %}
    {% endif %}
    {% endfor %}
</div>


<div class="widget features-slide-widget">
    <div class="title-section">
        <h1><span>SPIRITUALITE</span></h1>
    </div>
    {% for element in spiritualite_articles %}
    {% if element.article_categorie == "spiritualite" %}
    {% if forloop.counter == 1 and element != article %}

    <div class="news-post standard-post2">
        <div class="post-gallery">
            <img src="{{element.image.url}}" alt="">
        </div>
        <div class="post-title">
            <h2><a href="{% url 'home:article' element.id %}">{{element.title}}</a></h2>
            <ul class="post-tags">
                <li><i class="fa fa-clock-o"></i>{{element.date| date:"d F Y"}}</li>
                <li><i class="fa fa-user"></i>Par <a href="#">{{element.author}}</a></li>
                <li><a href="#"><i class="fa fa-comments-o"></i><span>{{element.comments_num}}</span></a></li>
                <li><i class="fa fa-eye"></i>{{element.post_views}}</li>
            </ul>
        </div>
    </div>
    <br>
    {% endif %}
    {% endif %}
    {% endfor %}
</div>



<div class="widget tab-posts-widget">

    <ul class="nav nav-tabs" id="myTab">
        <li class="active">
            <a href="#option1" data-toggle="tab">On en parle aussi</a>
        </li>
        <li>
            <a href="#option2" data-toggle="tab">International</a>
        </li>
        <li>
            <a href="#option3" data-toggle="tab">Culture</a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane active" id="option1">
            <ul class="list-posts">
                {% for element in articles %}
                {% if element.article_categorie != "politique" %}
                {% if forloop.counter >= 1  and forloop.counter < 7 %}
                <li>
                    <img src="{{element.image.url}}" alt="">
                    <div class="post-content">
                        <h2><a href="{% url 'home:article' element.id %}">{{element.title}}</a></h2>
                        <ul class="post-tags">
                            <li><i class="fa fa-clock-o"></i>{{element.date| date:"d F Y"}}</li>
                        </ul>
                    </div>
                </li>
                {% endif %}
                {% endif %}
                {% endfor %}
                <li>
            </ul>
        </div>
        <div class="tab-pane" id="option2">
            <ul class="list-posts">
                {% for element in international_articles %}
                {% if forloop.counter < 6 %}
                <li>
                    <img src="{{element.image.url}}" alt="">
                    <div class="post-content">
                        <h2><a href="{% url 'home:article' element.id %}">{{element.title}} </a></h2>
                        <ul class="post-tags">
                            <li><i class="fa fa-clock-o"></i>{{element.date| date:"d F Y"}}</li>
                        </ul>
                    </div>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="tab-pane" id="option3">
            <ul class="list-posts">
                {% for element in culture_articles %}
                {% if forloop.counter < 6 %}
                <li>
                    <img src="{{element.image.url}}" alt="">
                    <div class="post-content">
                        <h2><a href="{% url 'home:article' element.id %}">{{element.title}} </a></h2>
                        <ul class="post-tags">
                            <li><i class="fa fa-clock-o"></i>{{element.date| date:"d F Y"}}</li>
                        </ul>
                    </div>
                </li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>